### ISSUE TITLE
Using @import causes many network fetches and defeats browser style caching in Chrome

### ISSUE THREAD

**Issue by esprehn** [Wildhoney/ReactShadow#1]
Chrome (as of this writing version 42) can't cache and de-duplicate style blocks that contain @import statements inside ShadowRoots.

This means that each react component will download the .css file if it doesn't have cache headers, and that the browser won't de-duplicate the <style&gt; declarations which means creating those components will be really expensive as each one is parsing the stylesheet again.

Instead you want to write the css inline, or I suppose xhr it down and cache the string.

**Comment by Wildhoney** [comment]
Thanks for raising the issues, Elliot! :+1: I will look at this one a little later.

**Comment by pablinos** [comment]
I was wondering about all the server requests even if this caching issue didn't exist.
Maybe a solution to this issue though is to use one style tag and group insert the @import statements as needed?

**Comment by Wildhoney** [comment]
Polymer addressed this issue with [their Vulcanize tool](https://github.com/polymer/vulcanize), but I'm not entirely sure how that's going to behave with React components. However it would considerably reduce server requests in production.

**Comment by esprehn** [comment]
Note that you don't really want to use @import in production anyway because the async fetch of the sheet will cause FOUC.

**Comment by tjwudi** [comment]
It will be fantastic to add support for pure CSS source and drop support for `cssDocuments` as a function. You can take at look at my fork impl at [tjwudi/react-shadow-dom](tjwudi/react-shadow-dom).
This helps a lot because we can then build a **grunt** or **gulp** plugin for react-shadow, which automatically read and insert css rules into javascript.
In this case, you don't even need to fetch any css anymore, in production.

**Comment by Wildhoney** [comment]
@tjwudi How would adding the `cssSource` property differ from writing the styles inline as part of the React component? Although I think I understand what you're trying to achieve. Do you imagine as part of the build process, transferring all of the CSS styles from the documents defined in `cssDocuments` into the `cssSource` property?

**Comment by tjwudi** [comment]
Right. Component design is good for development, but we will always want to pack them into a big package in delivery. We sure can use css **@import** at development stage. Then we inline all css source in the building stage.

**Comment by Wildhoney** [comment]
Agreed. In that case I'm happy to merge in your `cssSource` changes from your forked branch, if you want to go ahead and open a PR for it :+1:

**Comment by tjwudi** [comment]
Of course I would :)
