### ISSUE TITLE
Heavy bundle size with styled components

### ISSUE THREAD

**Issue by fabricio7p** [Wildhoney/ReactShadow#104]
I'm making a embedabble widget with Preact + Styled components and ShadowDOM is a must for me
But after implementing it i pretty much doubled my bundle size due to some required nodejs libs.

Here's a bundle analyzer ss:
![image](https://user-images.githubusercontent.com/46208058/105846744-60a6cf80-5fbb-11eb-8278-fd48d9274bd2.png)

Apparently react-shadow is pulling again a 78kb styled-components package, is that expected? Seems like it doesn't recognize that i already have styled-components installed...

Also, as you can see, readable-stream and buffer are really heavy libs to pack into a tiny preact chatbot widget. Can you guys give me some guidance on reducing bundle size with react-shadow?

**Comment by fabricio7p** [comment]
Okay so i managed to port the source code into my application and saved about 100kb of bundle size.

**Comment by Wildhoney** [comment]
Not too sure about why it's pulled in `styled-components`. I added `react-dom/server` to externals which has reduced `dist/styled-components.js` to 5.9k.
