### ISSUE TITLE
React.addons.LinkedStateMixin incompatibility

### ISSUE THREAD

**Issue by tamascsaba** [Wildhoney/ReactShadow#11]
Hy!

I want to use React.ReactShadow with LinkedStateMixin, but it doesn't work, the state dont updateing.
No errors in console :(

Example:
http://jsbin.com/donaponata/1/edit?js,output

Working without ReactShadow:
http://jsbin.com/xaxigepacu/1/edit?js,output

I use React 0.12.2

**Comment by Wildhoney** [comment]
Removing mixins in https://github.com/Wildhoney/ReactShadow/tree/react-15.0
