### ISSUE TITLE
Add support for Babel+Browserify

### ISSUE THREAD

**Issue by bcherny** [Wildhoney/ReactShadow#12]
This works:

```js
import React from 'react'
import ReactShadow from 'react-shadow'

export default React.createClass({
  mixins: [ReactShadow],
  cssDocuments: ['styles/style.css'],
  render: function() { ... }
})
```

This does not:

```js
import React from 'react'
import ReactShadow from 'react-shadow'

export default class FavList extends React.Component {
  mixins: [ReactShadow]
  cssDocuments: ['styles/style.css']
  constructor (_) {
    super(_)
  }
  render() { ... }
}
```

**Comment by Wildhoney** [comment]
When using the ES6 syntax in `0.13.x` &ndash; [React doesn't support mixins](https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html) and therefore `ReactShadow` is never going to work.

I'm currently [working on Maple.js](https://github.com/Wildhoney/Maple.js) which is a module to support HTML Imports, Shadow DOM, and Custom Elements in React, which currently **only** supports the ES6 syntax &ndash; as opposed to the ES5 equivalent.

**Comment by Wildhoney** [comment]
Will be fixed when [updated codebase](https://github.com/Wildhoney/ReactShadow/tree/react-15.0) for `15.x` is released.
