### ISSUE TITLE
Heroku example does not work in Firefox

### ISSUE THREAD

**Issue by theogravity** [Wildhoney/ReactShadow#15]
Getting a `TypeError: this.getDOMNode(...).parentNode.createShadowRoot is not a function` when loading the page. 

http://caniuse.com/#feat=shadowdom

Might need to detect and use `webkitCreateShadowRoot()` instead as seen here:

http://soledadpenades.com/2014/01/02/shadow-dom-in-firefox/

Edit: looks like Firefox Nightly with a flag is required to use :(

**Comment by Wildhoney** [comment]
Will definitely add that :+1: although I would also recommend using [the WebComponents polyfill](https://github.com/webcomponents/webcomponentsjs), which should make `ReactShadow` available in all browsers.

If you're interested in React + WebComponents, maybe you'd also like [Maple](https://github.com/Wildhoney/Maple.js) that I created after `ReactShadow`, which covers a lot of the downfalls in this module &ndash; albeit more complex.
