### ISSUE TITLE
Event retargeting doesn't work on react-bootstrap modal

### ISSUE THREAD

**Issue by yuanfeiz** [Wildhoney/ReactShadow#16]
Using react-bootstrap modal and ReactShadow, I have a rendered DOM like this

```
<div>
  #shadow-root<open>
  <main>
    <div data-reactid=".2">
     <div data-reactid=".1">
       <div data-reactid=".1.1">
       </div>
     </div>
    </div>
  </main>
  <script> 
    <div data-reactid=".4">
     <div data-reactid=".3">
       <div data-reactid=".3.1">
       </div>
     </div>
    </div>
  </script>
</div>
```

The `translatedId` doesn't really get mapped correctly, as `.1.1` will be replaced as `.4.1` rather than `.3.1`. I wonder if there is any solution that is based on `event.path` rather than finding the element by `reactid`?

Besides, thank you for the great work!

**Comment by Wildhoney** [comment]
No event retargeting needed in https://github.com/Wildhoney/ReactShadow/tree/react-15.0

**Comment by trickpattyFH20** [comment]
@Wildhoney could you explain a little bit how ReactShadow handles this solution and avoids having to rebind the events? After reading through the source I'm having trouble seeing how you achieved this.

**Comment by Wildhoney** [comment]
It works because of the [`render` directly into the shadow boundary](https://github.com/Wildhoney/ReactShadow/blob/react-15.0/src/react-shadow.js#L74).
