### ISSUE TITLE
Seems like not working in react 15

### ISSUE THREAD

**Issue by DimitryDushkin** [Wildhoney/ReactShadow#18]
Errors:
```
Uncaught TypeError: Cannot read property 'createShadowRoot' of null
TypeError: this._shadowRoot.querySelector is not a function(…)
```

Chrome 51

**Comment by vhmth** [comment]
Same issue here.

**Comment by vhmth** [comment]
Also if you change:

```
ReactDOM.findDOMNode(this.parentNode).createShadowRoot()
```

to

```
ReactDOM.findDOMNode(this).parentNode.createShadowRoot()
```

you get errors about `React.render` being called. If you change those calls to `ReactDOM.render`, you run into the [Only a ReactOwner can have refs.](https://github.com/Wildhoney/ReactShadow/issues/6) issue.

@DimitryDushkin is it safe to say this repo is no longer maintained?

**Comment by DimitryDushkin** [comment]
@vhmth Have no idea about this repo status.

However I found correct solution to make React work with Shadow DOM — https://gist.github.com/DimitryDushkin/c091d5a6c33e10641eef0828261d5398

**Comment by Wildhoney** [comment]
I can look at upgrading `ReactShadow` to React 15 as they did make changes that would affect it. However I implemented Shadow DOM in [Keo](https://github.com/Wildhoney/Keo) using React 15 which works perfectly fine, and so you could use that if it, although it is a little more in-depth than this module.

**Comment by Wildhoney** [comment]
@DimitryDushkin do you want to send in a PR, please?

**Comment by DimitryDushkin** [comment]
@Wildhoney I cannot promise, but I'll try because at the moment I'm not totally satisfied with solution provided in [gist](https://gist.github.com/DimitryDushkin/c091d5a6c33e10641eef0828261d5398).

**Comment by Wildhoney** [comment]
Okay, thanks.

You can take a look at how I [implemented it for Keo](https://github.com/Wildhoney/Keo/blob/master/src/mixins/shadow.js#L46). It needs a little updating as it's using Shadow DOM v0's `createShadowRoot` rather than `attachShadow`, but everything else should still be valid.

**Comment by vhmth** [comment]
Thank you for both solutions guys! Will let you know what I go with.

**Comment by vhmth** [comment]
@Wildhoney trying to adopt what's in Keo to some of our components. Tried to set it up in the following way:

```
const MyComponent = class extends Component {
  ...
};
export default compose(shadow(), ({ props }) => {
  return <MyComponent { ...props } />;
});
```

Now when I try to render that component, `getContainer` throws an error saying it can't read `length` of `undefined` (`this.props.component.children` is undefined apparently). I feel like I'm doing something dumb. :P

**Comment by vhmth** [comment]
Hmm seems like when I do change the component out to this:

```
export default compose(shadow(), ({ props }) => {
  return <p>Hello, world!</p>;
});
```

It does render correctly, but that now throws errors like this:

```
Invariant Violation: _registerComponent(...): Target container is not a DOM element.
```

**Comment by vhmth** [comment]
Hmm another update, in the example above I simply copy/pasta'd the `shadow` component. When I `npm i keo` and then `import { shadow } from 'keo';` and use that, I'm getting the following error:

```
Error in event handler for (unknown): Invariant Violation: traverseParentPath(...): Cannot traverse from and to the same ID, ``.
```

Which is coming from `componentDidMount` when calling `ReactDOM.findDOMNode(this)`.

**Comment by Wildhoney** [comment]
@vhmth you were almost there with the `length` error, as I believe that relates to the `cssDocuments` props not being passed. I encountered the same issue.

I've gone ahead and created a [`react-0.15`](1.0.0-beta) branch (on npm: `1.0.0-beta`) to update the codebase for React 15.x. It no longer uses the mixin approach as that's *somewhat* deprecated. It instead uses Keo with a few optimisations and tweaks:

```javascript
import ShadowDOM from 'react-shadow';
```

```html
<ShadowDOM cssDocuments="css/my-component.css">
    <h1>Testing...</h1>
</ShadowDOM>
```

**Comment by Wildhoney** [comment]
Merged.

**Comment by vhmth** [comment]
Sweet! :D I completely forgot to come back to this - this is working like a charm now! Thank you so much Adam!

**Comment by Wildhoney** [comment]
Ahh I'm glad! Thanks @vhmth
