### ISSUE TITLE
Shadow DOM v1

### ISSUE THREAD

**Issue by kevinSuttle** [Wildhoney/ReactShadow#23]
Wondering how much of the v1 SDOM spec is supported here.

https://github.com/polymer/polymer/tree/2.0-preview#scoped-styling
https://developers.google.com/web/fundamentals/getting-started/primers/shadowdom

**Comment by Wildhoney** [comment]
None at the moment, but v1 is being implemented alongside v0 &ndash; Opera and Chrome **both** support `createShadowRoot` and `attachShadow`, but Firefox is **only** `createShadowRoot`.

I will move across soon, but don't worry too much about it at the moment.

**Comment by Wildhoney** [comment]
Will use `attachShadow` if it's available.
