### ISSUE TITLE
Help why include is not working and how to use props.theme

### ISSUE THREAD

**Issue by micchyboy** [Wildhoney/ReactShadow#27]
@Wildhoney 
I have this simple rendering of shadow DOM

`render() {
    return (
      <ShadowDOM include={['test.css']}>
      <div>
        <input type="text" value={this.props.templateName} onChange={this.handleChange.bind(this)}/>
        <button onClick={this.saveTemplate.bind(this)}>SAVE</button>
      </div>
      </ShadowDOM>
    );
  }`

Could you help me why the css not reflecting in test.css?

test.css
`:host input{
	width: 300px;
}
`

Also what is the purpose of props.theme? The documentation doesn't really explain its purpose

**Comment by Wildhoney** [comment]
@micchyboy it looks fine to me &ndash; there's no reason why it wouldn't work, considering the CSS is being successfully loaded. Check your network tab, and then inspect the shadow boundary to ensure it contains the expected `style` tag with your **test.css** content.

The `props.theme` is not part of `ReactShadow` but part of the example. It's simply pointing out that the `include` prop could be either an array:

```javascript
include: PropTypes.oneOfType([PropTypes.string, PropTypes.array])
```

**Comment by micchyboy** [comment]
Thanks man. Its working fine now. Btw is there a way to only render once the css has been loaded?

**Comment by Wildhoney** [comment]
👍 I wish &ndash; async React components is a deeper topic than `ReactShadow`, but we do have [the class name approach](https://github.com/Wildhoney/ReactShadow#avoiding-foic), so you could hide your component until it's `resolved`.

**Comment by herodrigues** [comment]
@Wildhoney could you explain how to do that?

I using your library in a Chrome extension and it's essential that CSS documents load before the HTML content.

**Comment by Wildhoney** [comment]
@herodrigues it's probably better to refer to the example.

[In the example](http://react-shadow.herokuapp.com/) the component renders as soon as it can, however it appears only once the CSS has been loaded using the [following CSS styles](https://github.com/Wildhoney/ReactShadow/blob/master/example/css/default.css#L20-L29) 👍

**Comment by herodrigues** [comment]
@Wildhoney I understood how fetching mechanism works in your library. I solved my issue by putting the desired CSS in my [manifest.json](https://developer.chrome.com/extensions/manifest) file. Thus, the style is injected before the DOM is loaded.
