### ISSUE TITLE
Firefox and IE support

### ISSUE THREAD

**Issue by micchyboy** [Wildhoney/ReactShadow#28]
Hi @Wildhoney ,

Seems Im getting some issues on IE and Firefox

`node.createShadowRoot is not a function`

Is this only built for chrome??

**Comment by Wildhoney** [comment]
See [support](http://caniuse.com/#feat=custom-elements). However there's a very good [polyfill](https://github.com/webcomponents/webcomponentsjs) for webcomponents 👍
