### ISSUE TITLE
Cannot use <Link> inside shadow dom component

### ISSUE THREAD

**Issue by micchyboy** [Wildhoney/ReactShadow#29]
I have an issue using react links inside the shadow dom component like this

`<ShadowDOM include={['/zion_resources/widgets/header.css']}>
      <div>
        <Link className="item" activeClassName="active" to="preview">
          <img src="/img/icons/zion.icon.tb_tablet.svg" alt="" width="23px"/>
        </Link>
      </div>
      </ShadowDOM>`

Throws an error <Link>s rendered outside of a router context cannot navigate.

Any workarounds for this?

**Comment by Wildhoney** [comment]
All fixed in `>=2.0.0` 👍
