### ISSUE TITLE
get node in Shadow DOM

### ISSUE THREAD

**Issue by awwester** [Wildhoney/ReactShadow#35]
I'm having issues integrating a react app in the shadow dom with packages that use the [ReactDOM.findDOMNode](https://facebook.github.io/react/docs/react-dom.html#finddomnode) function to access a specific node in the react app.

That function will definitely not be used since the app is in the shadow dom, however I'm curious if anyone has ran into this and what you use for the workaround to access the node by its ref?

**Comment by Wildhoney** [comment]
Is this any better with React 16.x @awwester? I've just done a quick test, and it seems to be fine. However there could be more complex cases that I haven't tested.

**Comment by awwester** [comment]
@Wildhoney I'll be circling back to this asap. Thanks for the heads up.

**Comment by Wildhoney** [comment]
Please try again with the new version.
