### ISSUE TITLE
Make font works in shadow dom

### ISSUE THREAD

**Issue by goffle** [Wildhoney/ReactShadow#37]
Hello,

I would like to use shadow dom and add icons inside this shadow dom but I can't make it works. 

```javascript ReactDOM.render(
    <div>
        <ShadowDOM include={['https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css']}>
            <div>
                <i className="fa fa-comments fa-2x"></i>icon
            </div>
        </ShadowDOM >
    </div>
    , document.getElementById('root'));`
```

When running the code above, I have a square icon. It seems the font itself is missing.  How can I add the font ?

Thanks for the help

**Comment by Wildhoney** [comment]
It actually seems to work for me @goffle 👍 

Tested in Chrome and Opera.

**Comment by Wildhoney** [comment]
Should work just fine with the updated version.

**Comment by wontwon** [comment]
I can't quite figure out how to get font-awesome to import correctly into my shadow dom. I tried using the same code as above, but was unsuccessful.

**Comment by Wildhoney** [comment]
You just need to import the CSS document into the shadow root: https://codesandbox.io/s/dark-voice-snrrc?file=/src/App.js

**Comment by wontwon** [comment]
@Wildhoney Thanks for your quick response! I'm not sure if the link you sent me is working. This is what I am currently seeing when I open your link. 

![2020-08-02 08 35 57](https://user-images.githubusercontent.com/3239936/89126563-4cb26300-d49b-11ea-9502-cda0c7a019ad.gif)

Do you see something different?

**Comment by Wildhoney** [comment]
Hmm yep: https://imgur.com/jOjJ8vk

Anything in the console such as the fonts failing to load?

**Comment by wontwon** [comment]
Weird @Wildhoney. I'm not seeing any requests to font-awesome. Here's my logs and network tab.

![2020-08-02 10 07 53](https://user-images.githubusercontent.com/3239936/89128120-2fd05c80-d4a8-11ea-8ddc-ffd373e95448.gif)
![2020-08-02 10 08 41](https://user-images.githubusercontent.com/3239936/89128122-3232b680-d4a8-11ea-9b79-5f2f502ef247.gif)

**Comment by wontwon** [comment]
Can confirm. Had a friend open your link @Wildhoney on his machine and just a squared showed instead of the icon. Not sure whats going on.

**Comment by Wildhoney** [comment]
Sorry maybe it's because I put `class` instead of `className?` Although still strange how it showed for me.

Is this any better: https://codesandbox.io/s/pedantic-colden-h6qtt

**Comment by ivnmaksimovic** [comment]
Using Chrome browser, I can see only square on this link [](https://codesandbox.io/s/pedantic-colden-h6qtt). And I do see font downloaded successfully in network tab. But just tried in Safari and I can see the camera icon.

**Comment by Wildhoney** [comment]
Is your version of Chrome somewhere around `84.0.4147.105`?

**Comment by ivnmaksimovic** [comment]
Chrome is Version 84.0.4147.105 (Official Build) (64-bit). If I change root.div to div, I can see the camera icon.
