### ISSUE TITLE
ReactShadow fails to run when used with browserify

### ISSUE THREAD

**Issue by ziahamza** [Wildhoney/ReactShadow#4]
ReactShadow currenlty throws an error at runtime when used under browserify with React. It tries to use window.React which doesnt exist. A small shim to work with browserify will be very nice.

**Comment by ziahamza** [comment]
This still doesnt fix the issue, under browserify each module needs to include the dependencies through: var React = require('react');

React guys provide a browser library under dist, but also a library for browserify as index.js which can be required by node and browserify modules.

**Comment by ziahamza** [comment]
for now I am manually putting react on the window to fix this: window.React = require('react')

**Comment by Wildhoney** [comment]
Sorry I misunderstood the first time around! The modue [now brings in React](https://github.com/Wildhoney/ReactShadow/blob/master/component/ReactShadow.js#L8) as a dependency if `require` is defined.

**Comment by henriklundgren** [comment]
Yeah, please provide Browserify support.

Maybe something like,...

var root = typeof exports !== 'undefined' && exports !== null ? exports : $window;
root.ReactShadow = {};

Using it:
var ReactShadow = require('react-shadow').ReactShadow;
// or
import {ReactShadow} from 'react-shadow';

**Comment by Wildhoney** [comment]
Yep, no problem. I'll do that soon.
