### ISSUE TITLE
componentWillUnmount of children not invoked when ShadowDOM unmounted

### ISSUE THREAD

**Issue by javadoug** [Wildhoney/ReactShadow#40]
Sample code to illustrate the issue provided below. Basically, ShadowDOM is eating the componentWillUnmount propagation somehow. This prevents binding events to the DOM. Is this by design?

	/*
	index.js {
	
		import React from 'react'
		import {init} from "./ShadowDomBug"
		init();
	
		// press Unmount Me button to remove component from DOM
	
		// expected console:
		// ShadowDomBug.js:66 ini
		// ShadowDomBug.js:72 unMountShadowDomBug
		// ShadowDomBug.js:9 1 BindDOMEventListeners
		// ShadowDomBug.js:9 1 BindDOMEventListeners
		// ShadowDomBug.js:21 2 AnotherBindDOMEventListeners
	
		// actual console:
		// ShadowDomBug.js:66 ini
		// ShadowDomBug.js:72 unMountShadowDomBug
		// ShadowDomBug.js:9 1 BindDOMEventListeners
	
	}
	*/
	import React, {Component} from 'react';
	import ReactDOM from 'react-dom'
	import PropTypes from 'prop-types'
	import ShadowDOM from 'react-shadow'
	
	class BindDOMEventListeners extends Component {
		componentWillUnmount() {
			// called every time
			console.log('1 BindDOMEventListeners')
			// window.removeEventListener('keydown', ...);
		}
	
		render() {
			return (<div>{this.props.children}</div>);
		}
	}
	
	class AnotherBindDOMEventListeners extends Component {
		componentWillUnmount() {
			// never called
			console.log('2 AnotherBindDOMEventListeners')
			// window.removeEventListener('keydown', ...);
		}
	
		render() {
			return (<div> no children </div>);
		}
	}
	
	export class ShadowDomBug extends Component {
		render() {
			return (
				<BindDOMEventListeners>
					<ShadowDOM>
						<div>
							<BindDOMEventListeners>
								<AnotherBindDOMEventListeners/>
								<div>
									<button onClick={this.props.unMountMe}>Unmount Me</button>
								</div>
							</BindDOMEventListeners>
						</div>
					</ShadowDOM>
				</BindDOMEventListeners>
			);
		}
	}
	
	ShadowDomBug.propTypes = {
		unMountMe: PropTypes.func
	};
	
	ShadowDomBug.defaultProps = {
		unMountMe: unMountShadowDomBug
	};
	
	export const domRootId = 'ShadowDomBug';
	
	export function init() {
		let root = document.getElementById(domRootId);
		if (!root) {
			root = document.createElement('div');
			root.id = domRootId;
			root.setAttribute('id', domRootId);
			document.body.appendChild(root);
			console.log('ini')
			ReactDOM.render(<ShadowDomBug/>, root);
		}
	}
	
	export function unMountShadowDomBug() {
		console.log('unMountShadowDomBug')
		ReactDOM.unmountComponentAtNode(document.getElementById(domRootId))
	}

**Comment by Wildhoney** [comment]
I've setup a quick example and `componentWillUnmount` works as expected when a child of `<ShadowDOM />` is removed, using `React@16.1.0`.
