### ISSUE TITLE
high order component props do not pass down to child components

### ISSUE THREAD

**Issue by javadoug** [Wildhoney/ReactShadow#41]
I am using a MuiThemeProvider from 'material-ui/styles/MuiThemeProvider' that passes a prop to components that subscribe using muiThemeable from 'material-ui/styles/muiThemeable'. However, the Provider props are not passed thru the ShadDOM down to children. Workaround is to wrap Provider again after ShadowDOM. Which is OK for for me however, propagating the props would be more elegant. Is this by design?

**Comment by Wildhoney** [comment]
Props [are passed down](https://github.com/Wildhoney/ReactShadow/blob/master/src/react-shadow.js#L294).

**Comment by javadoug** [comment]
MuiThemeProvider use [ReactJS Context](https://reactjs.org/docs/context.html), perhaps the issue is related to this. My workaround is to output the MuiThemeProvider again in my Shadow component but this is not a long term fix as the component has to "know" which theme to use. The error that is given inside my muiThemeable component is the muiTheme prop is missing, which is why I thought it was a props passing issue.

**Comment by Wildhoney** [comment]
Take a look at the [`withContext` HOC](https://github.com/Wildhoney/ReactShadow/blob/master/src/react-shadow.js#L312) that's bundled &ndash; by default it's setup to only pass down the `router` context (for `react-router`), but you could import the `withContext` HOC and set it up for MuiThemeProvider.

**Comment by jasco** [comment]
@Wildhoney Is there an example available of how to use `withContext`?

**Comment by Wildhoney** [comment]
Should work just fine with the updated version without the `withContext` approach.
