### ISSUE TITLE
first child of ShadowDOM cannot be a custom component

### ISSUE THREAD

**Issue by javadoug** [Wildhoney/ReactShadow#42]
We get the error message: "ReactShadow: Passed child must be a concrete HTML element rather than another React component."

	/*
	index.js {

		import React from 'react'
		import {init} from "./ShadowDomBug"
		init();

		// expected  output
		// hello, world

		// actual output error
		// ReactShadow: Passed child must be a concrete HTML element rather than another React component.
	}
	*/

	import React, {Component} from 'react';
	import ReactDOM from 'react-dom'
	import ShadowDOM from 'react-shadow'

	class MyComponent extends Component {
		render() {
			return (<div>{this.props.children}</div>);
		}
	}

	export class ShadowDomBug extends Component {
		render() {
			return (
				<ShadowDOM>
					<MyComponent>
						<div>
							hello, world
						</div>
					</MyComponent>
				</ShadowDOM>
			);
		}
	}

	export const domRootId = 'ShadowDomBug';

	export function init() {
		let root = document.getElementById(domRootId);
		if (!root) {
			root = document.createElement('div');
			root.id = domRootId;
			root.setAttribute('id', domRootId);
			document.body.appendChild(root);
			console.log('ini')
			ReactDOM.render(<ShadowDomBug/>, root);
		}
	}

**Comment by Wildhoney** [comment]
Yes, the immediate child of `<ShadowDOM />` cannot be `<MyComponent />`, but rather a concrete HTML node:

```javascript
<ShadowDOM>
  <div>
    <MyComponent>
      <div>
        hello, world
      </div>
    </MyComponent>
  </div>
</ShadowDOM>
```
