### ISSUE TITLE
Object doesn't support property or method createShadowRoot - Edge

### ISSUE THREAD

**Issue by basherr** [Wildhoney/ReactShadow#45]
The `ShadowDom` doesn't seem to work on edge? I've also tried adding pollyfill but that didn't fix too.

```
public render() {
    console.log("application state:", this.props);

    try {
      return (
        <div>
          <ShadowDOM include={ browser.extension.getURL('/styles/main.css') }>
            <div>
              {this.currentPanel()}
            </div>
          </ShadowDOM>
        </div>
      );
    } catch (ex) {
      console.log(ex);
      throw ex;
    }
  }
```
Please suggest
Thanks

**Comment by Wildhoney** [comment]
Do you get the same error with the [polyfill](https://github.com/webcomponents/webcomponentsjs)

**Comment by basherr** [comment]
@Wildhoney The error doesn't seem to change even having pollyfill

**Comment by funkizer** [comment]
Wasn't createShadowRoot deprecated a long time ago?

**Comment by basherr** [comment]
@funkizer It is deprecated but pollyfill seems to fix this issue with firefox but not with edge.

**Comment by funkizer** [comment]
Yeah. Polyfills aren't meant to return dropped features. It was deprecated some 2 years ago in favor of: https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow

**Comment by Wildhoney** [comment]
It's only complaining about `createShadowRoot` [because it's the fallback](https://github.com/Wildhoney/ReactShadow/blob/master/src/react-shadow.js#L173).

Using `webcomponents-sd-ce.js` there should be no reason why `attachShadow` wouldn't be polyfilled.

**Comment by basherr** [comment]
@Wildhoney We however added the pollyfill for firefox which doesn't seems to work and we've tried changing `dom.webcomponents.enabled` to `true` in `about:config` section which seems to be fixed but as always it isn't solution to the problem. Could there anything I'm missing with `firefox 58.0`?

**Comment by Wildhoney** [comment]
The example [uses the polyfill](https://github.com/Wildhoney/ReactShadow/blob/master/example/js/default.js#L1).

It [seems to work just fine for me](http://react-shadow.herokuapp.com/) in Firefox 58.

**Comment by pactera-admindev-remy** [comment]
I did as you did, it fixed the createShadowRoot problem but another one poped up instead on Firefox.

*TypeError: Argument 1 of EventTarget.dispatchEvent does not implement interface Event.*

No problem on Chrome/Safari.

**Comment by Wildhoney** [comment]
Not supporting older versions of shadow roots any more.
