### ISSUE TITLE
The ShadoDom css issue with firefox

### ISSUE THREAD

**Issue by basherr** [Wildhoney/ReactShadow#48]
The Shadodom with unsupported browser like `firefox and edge` may cause trouble with **CSS** issues. As of [firefox documentation](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Status_in_Firefox) 
>A polyfilled Shadow DOM using the [webcomponents.js](https://github.com/webcomponents/webcomponentsjs) polyfill doesn't actually encapsulate style, so the styles might bleed through. Be aware that sites built using the polyfill might look different when running in an environment that does support native Shadow DOM.

We just encounterd the [CSS Issue](https://screenshots.firefox.com/jNYmgVkGzA0RWusu/www.cvs.com) when we were using `Shadow Dom` with `firefox` latest version.
Is there any work around for this?

**Comment by Wildhoney** [comment]
Have you tried the [`initial: all`](https://caniuse.com/#feat=css-initial-value) on each host node for style encapsulation?

**Comment by basherr** [comment]
Tried this but no success
```
const styles = `:host { initial: all }`;
return (
<div>
       <ShadowDOM include={ browser.extension.getURL('styles/main.css') }>
            <div>
                  {this.currentPanel()}
                 <style type="text/css">{styles}</style>
            </div>
      </ShadowDOM>
</div>
)
```

**Comment by trickpattyFH20** [comment]
@basherr try `all: initial` not `initial: all`
