### ISSUE TITLE
Keyboard events are not being emitted

### ISSUE THREAD

**Issue by ziahamza** [Wildhoney/ReactShadow#5]
Click events work beautifully, but ketboard events are displatched but never recieved by Reat

**Comment by Wildhoney** [comment]
We just need to add to the [list of events](https://github.com/Wildhoney/ReactShadow/blob/master/component/ReactShadow.js#L98) for keyboard events. There is an [outstanding issue](https://github.com/Wildhoney/ReactShadow/issues/6) with `ref` attribute though, which I need to find a workaround for.

**Comment by Wildhoney** [comment]
Could you try with [`v0.2.0`](https://github.com/Wildhoney/ReactShadow/commit/7456a3e46cb1f1ae4eb83ae39aaa8d3bda1eca34)?

**Comment by ziahamza** [comment]
Yeah, keyboard events are now emitting. But I still cant get the value of the text area, either from ev.target.value or using refs

**Comment by ziahamza** [comment]
I can get the value now using event.target.getAttribute('value') but somehow not otherwise. Although hacky but it works. Although now I have another bug where the button is always disabled, but I will add that separately
