### ISSUE TITLE
http://react-shadow.herokuapp.com/ is offline

### ISSUE THREAD

**Issue by diegonvs** [Wildhoney/ReactShadow#54]
Your demo is offline, see attached SS: ![image](https://user-images.githubusercontent.com/7663513/45581917-6a618980-b87d-11e8-95aa-aedd7d1dd3c4.png)

**Comment by Wildhoney** [comment]
Good spot. [It should be good now](https://react-shadow.herokuapp.com/). Thanks! 👍
