### ISSUE TITLE
Implement support for CSS Shadow Parts

### ISSUE THREAD

**Issue by paales** [Wildhoney/ReactShadow#55]
Since React seems to invent the wheel themselves in regards to styling, maybe it is interesting to take a look at the CSS Shadow Parts specification and see if that can be implemented / polyfilled.

https://drafts.csswg.org/css-shadow-parts/

**Comment by Wildhoney** [comment]
Thanks for this @paales. I haven't seen that spec before, and I actually do like the approach they're taking with styling. I'll wait for it to hopefully mature a little bit before deciding how it fits in with `ReactShadow` 👍

**Comment by Wildhoney** [comment]
Should work just fine with the new version. Thanks @paales!

**Comment by paales** [comment]
Cool!
