### ISSUE TITLE
Render react portal into shadow dom container

### ISSUE THREAD

**Issue by jschuler** [Wildhoney/ReactShadow#58]
Hi, is it possible to render a react portal into a shadow dom? I assigned an id to a div element within the ShadowDom but it cannot find it

**Comment by jschuler** [comment]
Seems like this could be new functionality that can be added? Maybe having a namespace in the document and then being able to assign shadow roots to it
```
if (!document.reactShadow) {
          document.reactShadow = {};
}
// if id is passed into ShadowDOM, we can assign the root to it, e.g. <ShadowDOM id="rootShadowDom"
if (this.props.id) {
  document.reactShadow[this.props.id] = root;
}
```
Then later could render portal in like this:
```
ReactDOM.createPortal(
      <div>My portal</div>,
      document.reactShadow.rootShadowDom
    );
```

**Comment by Wildhoney** [comment]
Hmm not sure about that &ndash; seems kinda quirky. You would need a reference to the actual shadow root, which you can then render your tree into.

I'm working on a re-write at the moment that will use `createPortal` to render into the shadow root, as that overcomes all of the pre-16 issues with the context being propagated down to the children.

**Comment by trungtin** [comment]
Not related to the issue but when can we expect the re-write to be available @Wildhoney? Thanks

**Comment by Wildhoney** [comment]
It’s out there already, @trungtin
