### ISSUE TITLE
Add TypeScript defintion

### ISSUE THREAD

**Issue by nmussy** [Wildhoney/ReactShadow#61]
Hey,

It'd be nice to add TypeScript definitions to the project. I can make a PR if needed.

EDIT: Looking at how compact the `src/` is, it might even be worth switching the project to TypeScript, if you feel up to it

**Comment by Wildhoney** [comment]
I'd rather keep it as standard JS.

Would be awesome to have a definition file though &ndash; thanks @nmussy!

**Comment by nmussy** [comment]
No problem, I'll probably make a PR tonight. It should be pretty easy to maintain, but you can @ me in the future if you need me to update it.

**Comment by Wildhoney** [comment]
Thank you @nmussy 👍

**Comment by sHooKDT** [comment]
Also wanted to use the package in TS, but ran into definitions absence.
I'm still not sure I need to use it, but if I decide, I can create definitions myself.

Any news on this? @nmussy

**Comment by nmussy** [comment]
Yeah, sorry about that, I hit a wall with the `root.div` part of the API. I
wanted to type check the NodeElement, but I might have to allow a generic
string.

I was going to look into it this weekend, but I'll ping you if I give up. 😁

**Comment by Wildhoney** [comment]
Any luck folks?

**Comment by nmussy** [comment]
Still haven't looked into it more, sorry. I'll open a PR with what I have so far tonight

**Comment by MalekBouba** [comment]
Same issue.. can we help?

**Comment by nmussy** [comment]
Yeah, sorry about that guys. I'm on holiday at the moment, I'll see what I
can do over the weekend

**Comment by yurist38** [comment]
I'm about to start using it and missing TS definitions too... If you guys have any draft of definitions and have no time to complete, please commit the stuff and let us know. Some of us can contribute to making it done, I'm pretty sure.

**Comment by yurist38** [comment]
I made my try in the end and that's what I ended up with for now:
```
declare module 'react-shadow' {
  import { ReactNode, ComponentType } from 'react';

  type RenderElement = keyof HTMLElementTagNameMap;

  type Root = {
    [name in RenderElement]: ComponentType;
  }

  const root: Root;

  export default root;
}
```

If you have any idea what is wrong or how I can improve these typings - please feel free to share!

**Comment by nmussy** [comment]
That's basically what I had in mind, but the issue with that is that you
could Shadow DOM a custom element.

**Comment by marijnbent** [comment]
Same problem here. Any luck fixing it?

**Comment by benji6** [comment]
@yurist38 your types were really helpful for me. I think this might be a slight improvement:

```typescript
declare module "react-shadow" {
  import * as React from "react";

  type RenderElement = keyof HTMLElementTagNameMap;

  type Root = {
    [name in RenderElement]: React.ComponentType<
      React.HTMLAttributes<HTMLElementTagNameMap[name]>
    >;
  };

  const ReactShadowRoot: Root;

  export default ReactShadowRoot;
}
```

I'm just passing a type argument of `React.HTMLAttributes<HTMLElementTagNameMap[name]>` to `React.ComponentType`. It's not quite right though because if the element is a button for instance we should be using `React.ButtonHTMLAttributes` instead of `React.HTMLAttributes`, but it did solve a type error I was getting.

**Comment by yurist38** [comment]
I've opened a PR based on the solution from @benji6 (thanks for that!). Let's see if it's going to be merged...

**Comment by Wildhoney** [comment]
@yurist38 just a question of how `HTMLElementTagNameMap` works if you're using custom elements? For example `root.myCustomElement` that yields a `<my-custom-element>` node is perfectly fine in `react-shadow`, whereas `HTMLElementTagNameMap` seems to be a map of only the standard HTML elements.

Wouldn't that cause issues? Do we need to allow for arbitrary `string` types, too?

**Comment by yurist38** [comment]
@Wildhoney yes, your concern was correct. Just tested it locally, it doesn't work with a custom element. So I think you're right and we have to make it less strict... I'm opening a PR with refactoring to `string`.
