### ISSUE TITLE
Usage with styled-components

### ISSUE THREAD

**Issue by CodingDive** [Wildhoney/ReactShadow#62]
Hey, thank you for this wonderful library. 😍 	

Is there an example of how to use react-shadow with styled-components? I'm using client side React and my styles are not applied. I tried both options of styling a `React` component but the `border` prop doesn't even show up inside the styles of the devtools.

```JSX
import 'styled-components/macro'
const Test = () => <div css={`border: solid 1px black;`}>Test</div>
```

or via an actual styled-component:

```JSX
import styled from 'styled-components'
import root from 'react-shadow';

export const Test = styled.div`
  border: solid 1px black;
`

export default function ShadowStyles() {
    return (
        <root.div>
           <Test> Test </Test>
        </root.div>
    );
}
```

**Comment by Wildhoney** [comment]
Sadly `styled-components` applies all of its stylesheets to the document root, which means they the styles won't pass through the shadow boundaries. At the moment they don't seem to provide a way to re-target the stylesheets.

**Comment by mitchheddles** [comment]
I had a similar issue but got around it by following [this thread](https://github.com/styled-components/styled-components/issues/659).
Demo:
```js
import React from 'react';
import root from 'react-shadow';
// We need to use StyleSheetManager to catch and styled components and target them a node inside
// of the shadow DOM. Otherwise they will be on the document, therefore excluded.
import { StyleSheetManager } from 'styled-components';

// This component is used to determine if the shadow root children have been mounted,
// we can't assume they are mounted with the parent and using a timer is risky.
const DidMount = ({ onMount }) => {
  React.useEffect(onMount, []);

  return null;
};

export const MyShadowComponent = ({ children }) => {
  const node = React.useRef(null);
  const [mounted, setMounted] = React.useState(false);

  return (
    <root.div>
      <div ref={node}>
        <DidMount onMount={() => setMounted(true)} />
        {mounted && node.current && (
          <>
            <StyleSheetManager target={node.current}>
              <>{children}</>
            </StyleSheetManager>
          </>
        )}
      </div>
    </root.div>
  );
};
```

Usage:
```js
<MyShadowComponent>
  <MyStyledComponent>Hello</MyStyledComponent>
</MyShadowComponent>

```

**Comment by xdumaine** [comment]
I'm having the same issue with just using react inline styles, which also applies the stylesheet to the root.

**Comment by Wildhoney** [comment]
> I'm having the same issue with just using react inline styles, which also applies the stylesheet to the root.

Like [this](https://codesandbox.io/s/react-shadow-pgzzo)? As it seems okay.

**Comment by xdumaine** [comment]
Ahh sorry, we're using react-native-web with inline styles, so all inline styles get compiled to a single stylesheet appended to the document root, instead of truly inlined.

**Comment by Wildhoney** [comment]
Sorry @xdumaine I'm not sure about the library. Maybe others will have an idea.

Awesome solution @mitchheddles &ndash; I've implemented that into the core module using your approach starting with `v17.2.0`. Any time you create a new shadow boundary now, it also creates a new `StyleSheetManager` context so `styled-components` should just work without any additional steps.

**Comment by Wildhoney** [comment]
@xdumaine please raise a separate ticket if you haven’t yet found a solution 👍
