### ISSUE TITLE
getBoundingClientRect always returns null on first render

### ISSUE THREAD

**Issue by Spiderixius** [Wildhoney/ReactShadow#67]
Hello. I am working on being able to get the initial position and width/height of shadowDOM elements. If you look at this codesandbox <https://codesandbox.io/s/delicate-dust-77yqk> (courtesy of @asjas). As you can see on first load the width and height is `0, 0` and only after re-rendering that we can see the actual width and height.

**Comment by Wildhoney** [comment]
Will take a look. Any initial thoughts as to why it happens?

**Comment by Spiderixius** [comment]
I have no idea @Wildhoney my current solution has been to use LocalStorage to store on dragStart and go from there.
