### ISSUE TITLE
Clarification Around `styled-components` Support

### ISSUE THREAD

**Issue by joealden** [Wildhoney/ReactShadow#69]
I can see that built-in `styled-components` support was added in https://github.com/Wildhoney/ReactShadow/commit/637149b7215930e856d7619f651f7d6cc116d8a7, but I am wondering as this library depends on `styled-components` directly (as seen [here](https://github.com/Wildhoney/ReactShadow/blob/264d3593e7ebb2944c30f4471f6dfae4b2052da1/package.json#L79)), would this not mean that the `StyleSheetManager` created [here](https://github.com/Wildhoney/ReactShadow/blob/264d3593e7ebb2944c30f4471f6dfae4b2052da1/src/index.js#L12-L13) would always be the `StyleSheetManager` coming from the `styled-components` version this library depends on (currently v4.4.1), not the version that the user of this library is depending upon (potentially `styled-components` v5+)?

I may be overlooking the following, so let me know if these measures mean that the version the library renders is indeed the version the user of the library is depending upon:

- The fact that you are using `require`, instead of importing it statically.
- The fact that the `styled-components` version you are depending on in this library is a dev dependency (which might only be being actually used in the examples, and it isn't part of the build output).

I ask this a I want to update `react-shadow` to v14.2.0+, and `styled-components` to v5, but I want to make sure that its not going to introduce any weird bugs because the `StyleSheetManager` injected isn't coming from the same `styled-components` version as the components I'm creating.

Thanks for your time!

**Comment by Wildhoney** [comment]
Yes `react-shadow` will use the version that is local to your project.

You can confirm this by looking [at the sandbox](https://codesandbox.io/s/react-shadow-by6bo) and finding the `data-styled-version` attribute of the quote &ndash; it will be `4.4.1`. Then upgrade `styled-components` on the left to `5.0.0` and re-inspect, the shadow root should have the `data-styled-version` attribute again, but this time be equal to `5.0.0`.

**Comment by joealden** [comment]
@Wildhoney great, thanks for the really simple example to show that this is actually the case! I'll go ahead and close this issue then :)
