### ISSUE TITLE
Add support for nested shadow roots

### ISSUE THREAD

**Issue by Wildhoney** [Wildhoney/ReactShadow#7]

**Comment by bcherny** [comment]
+1 this make ReactShadow difficult to use in prod

**Comment by Wildhoney** [comment]
@bcherny it's something that's proving to be awfully difficult to implement with a simple mixin &ndash; that's why I've started the [Maple.js project](https://github.com/Wildhoney/Maple.js) to bring a more robust approach to HTML Imports, Shadow DOM, and Custom Elements to React. From my point of view, `ReactShadow` is a precursor to `Maple` and the former was always meant to be an experimental project to *test the water*.

**Comment by Wildhoney** [comment]
Use Maple instead.
