### ISSUE TITLE
Mixing import and require breaks when used with rollup 

### ISSUE THREAD

**Issue by issoweilsosoll1** [Wildhoney/ReactShadow#72]
When trying to get ReactShadow to work together with Rollup, I get a ReferenceError that require() is not defined for `const styled = require('styled-components');` Thus, when I bundle with Rollup, my StyledComponents css is still being added to the head tag instead of being added to the shadowDOM.

> Unfortunately, mixing import and require is a "Webpackism" that is not supported by Rollup. Rollup only understands ESM, importing CommonJS (which uses require) is handled by rollup-plugin-commonjs which will skip this file due to the presence of the import statement. - https://github.com/rollup/rollup-plugin-commonjs/issues/273#issuecomment-504758287

Would it be possible to get rid of the require() statement and use import instead?

**Comment by Wildhoney** [comment]
Yep I will be making that change a little later (moving to 3 separate files depending on your env) &mdash; see #73.

**Comment by Wildhoney** [comment]
Could you try `v18.0.0` please @issoweilsosoll1?

**Comment by Wildhoney** [comment]
Closing issue as I believe this has been fixed. Please feel to re-open if you're still having issues, @issoweilsosoll1.
