### ISSUE TITLE
onMouseEnter isn't fired on child components

### ISSUE THREAD

**Issue by LexSwed** [Wildhoney/ReactShadow#75]
Child components don't get `onMouseEnter` events attached

[Codesandbox](https://codesandbox.io/s/objective-kilby-jle3f?file=/src/App.js)

Sorry for brief issue, contact me for details, if needed. For now I'm gonna stick with `onMouseOver`

**Comment by Wildhoney** [comment]
Yeh, that's a tough one to solve as `mouseEnter` and `mouseLeave` are the few events that don't bubble at all.

**Comment by lucascurti** [comment]
@LexSwed @Wildhoney I'm just playing with `ReactShadow` and faced this problem. Seems that it doesn't work if the event is attached to a direct child of `root` but noticed that it works if you wrap the component in a `div` or something like that.
[Codesandbox](https://codesandbox.io/s/pedantic-ramanujan-f9zq7)
