### ISSUE TITLE
Styled-components not working in production

### ISSUE THREAD

**Issue by laurentC35** [Wildhoney/ReactShadow#76]
Hello,
I use react-shadow/styled-components and styled-components to style my react components.
When I use yarn start (react-scripts start), it works well.
But I build the app with yarn build (react-scripts build), it doesn't seem to be working anymore.
With dev-tools I can see the style tag, but it is empty.

react-shadow: 18.1.0
styled-components: 5.0.1

Navigator : on chrome and firefox (last-version)

Maybe I'm misusing both packages ?
Thanks

**Comment by Wildhoney** [comment]
Hmm that's a tough one to debug without seeing the code. Is the `style` tag an immediate descendant of the shadow root?

**Comment by laurentC35** [comment]
Hello again,

Yes the `style` tag is an immediate descendant of the shadow root.
I found finally a solution, I needed to call two times `ReactDOM.render(<App/>, ...)`, I've found a more elegant alternative. (with only one call to `ReactDOM.render(<App/>, ...)` ).

So the problem was the double-calling of this method. Sorry ;)

**Comment by Wildhoney** [comment]
Hmm why do you need to double call? Sounds like you're having a problem elsewhere, if you can describe the issue you're having, maybe I can help.

**Comment by everythinginjs** [comment]
We're experiencing the same issue. The <style> tag is empty with no CSS rulesets, yet on the initial mount we can see the styles being applied correctly. However, the <style> tag itself contains nothing. Upon any subsequent re-render, all styles are lost completely.

prod-like env:
<img width="1266" height="672" alt="Image" src="https://github.com/user-attachments/assets/c2e08f34-3034-47cb-bf7f-0b2c30b3f6c9" />

local:
<img width="1373" height="683" alt="Image" src="https://github.com/user-attachments/assets/94d96cf2-ad41-45d4-a6d7-885757ba97b0" />

**Comment by everythinginjs** [comment]
I tried using `StyleSheetManager` but no luck, 

Page.tsx
```
<root.div>
      <ShadowRootContent
        content={page.content}
        pageId={page.id}
        pageHeight={page.height}
        pageWidth={page.width}
        backgroundSize={page.backgroundSize}
      />
 </root.div>
```

ShadowRootContent.tsx

```
export function ShadowRootContent({
  content,
  pageId,
  backgroundSize,
  pageHeight,
  pageWidth,
}: ShadowRootContentProps) {
 /* I removed some internal and global states + click handlers + hooks to keep it short */


  return (
    <StyledPageContent
      id={pageId.toString()}
      onClick={onClickHandler}
      style={{
        width: utils.rem(width),
        height: utils.rem(height),
      }}
    >
      <StyledSvgContainer
        style={{
          transform: `scale(${zoom / 100})`,
          width: `${100 / (zoom / 100)}%`,
          height: `${100 / (zoom / 100)}%`,
        }}
        dangerouslySetInnerHTML={{
          __html: content,
        }}
      />
    </StyledPageContent>
  );
}
```

**Comment by everythinginjs** [comment]
any idea what's going on @Wildhoney?
