### ISSUE TITLE
mousedown event not working

### ISSUE THREAD

**Issue by maheshramaiah** [Wildhoney/ReactShadow#82]
Hi,
I am facing an issue with mousedown event.
Here is the code sandbox link to reproduce the issue: https://codesandbox.io/s/react-shadow-mosedown-e31k3?file=/src/index.js.

Basically, i have created an mousedown event on document. I expect the event.target to be element's container when event triggers but the target always reference to the shadow dom root.

Any suggestion would really help.

**Comment by Wildhoney** [comment]
That's due to [event retargeting](https://polymer-library.polymer-project.org/2.0/docs/devguide/shadow-dom#event-retargeting) which hides the implementation details of the nodes encapsulated in the shadow root.

**Comment by maheshramaiah** [comment]
Any way to fix it ?

**Comment by Wildhoney** [comment]
Tough, but you can try `e.composedPath()[0]` instead of `event.target`. Although with using `composedPath` you'll have to begin implementing custom logic to get the relevant node.
