### ISSUE TITLE
erases all styles for material-ui components

### ISSUE THREAD

**Issue by meerkat-citronella** [Wildhoney/ReactShadow#83]
Wrapping any material-ui component in a shadow root element (i.e. <root.div>) causes all the styles on that mui component to no longer show.

**Comment by meerkat-citronella** [comment]
nvm

**Comment by meerkat-citronella** [comment]
sorry, yes, this seems to be like a real issue. Although it may actually be a feature, not a bug. Please excuse my ignorance, i am new to React and programming in general.

**Comment by Wildhoney** [comment]
That’s all right @meerkat-citronella.

Could you setup an example with Codesandbox please? Might just be a case of adding the Material UI CSS to the shadow root rather than globally.

**Comment by meerkat-citronella** [comment]
sure can, thanks for the prompt reply!

here: https://codesandbox.io/s/amazing-goldstine-v57ec?file=/src/App.js

**Comment by meerkat-citronella** [comment]
i also tried implementing this [solution](https://stackoverflow.com/questions/54430119/how-to-mount-styles-inside-shadow-root-using-cssinjs-jss/56516753?fbclid=IwAR0vP6_gQWMykSPUUFawrCj8BbMTnsI3ZgwN-AJ8CkcN16LAEqmmFYuiOHo): (last answer) . The wrapper fixes the styles on the table, but not the button on codesandbox

**Comment by Wildhoney** [comment]
Good effort on the wrapping, but it does seem as though the button's styles are still applied outside of the shadow boundary, which is why it's unstyled.

We do have a couple of wrappers for `styled-components` and `@emotion` so I'll take a look at also implementing a `material-ui` version so hopefully you'll just be able to `import root from 'react-shadow/material-ui'` but that button still being unstyled despite the explicit `StyleSheetManager` is concerning.

**Comment by Wildhoney** [comment]
Have a play with `react-shadow@18.2.4` please &ndash; I've [updated your example](https://codesandbox.io/s/upbeat-poitras-tyhrh?file=/src/App.js) and everything seems to be working well.

I don't really use Material UI myself though, so there could be further problems. In the Material UI repo there are a few mentions of shadow DOM compatibility issues, but *some* may have been resolved already.

Also I'm not sure how to implement server-side rendering support for Material UI, so that's something else for me to look into, as their `StylesProvider` requires you pass in the `insertionPoint` which you wouldn't have server-side.

**Comment by meerkat-citronella** [comment]
Hey man, thanks for the solution. It works pretty well. Just wanted to follow up a bit... pulling back the curtain, the way that my team is trying to implement this is as part of a chrome extension. The extension targets input elements on the page, and then whenever an input is clicked on, it creates a dropdown with popper.js and fills it with some data. We came across react-shadow because we are trying to keep the dropdown styles consistent no matter what the styles on the page are; our idea was to render the dropdown into an instance of `<root.div>`. It seems like the fix you have works fine on the first render, but on subsequent renders, the styles are still stripped. See the [codesandbox](https://codesandbox.io/s/agitated-water-sz206?file=/src/App.js) for example (just click on the inputs to show the dropdown). My hunch is that it has something to do with how the shadow DOMs are interacting with one another... one can never actually delete an instance of a shadow DOM, right?  

I don't expect you to fix our specific implementation of your module, you've been enough help already, but just wanted to let you know how it's being used if it's helpful to you at all. I think we are just going to use styled-components and style all the tags manually, instead of using some library. But thanks for your help anyway, cheers!

**Comment by Wildhoney** [comment]
I setup [a simpler example](https://codesandbox.io/s/loving-williamson-2lxg4?file=/src/App.js) to re-render on click, and it does seem to maintain the styling. Suggests there may be something quirky in your example that's breaking the styles somehow?

**Comment by meerkat-citronella** [comment]
I didn't explain myself correctly lol. I said 'render' and 'subsequent render' but what I really meant was that there are still problems when we have more than one instance of a shadow root. I extended your [simpler example](https://codesandbox.io/s/zen-poincare-3e9nm?file=/src/App.js) to show what I'm talking about.

**Comment by Wildhoney** [comment]
Oh. Yah, in that case it looks to be an issue with Material UI only paying attention to the first `insertionPoint` &mdash; on second record it assumes it's already applied the styles, and so doesn't (re)-apply them to the other `insertionPoint`.

Hmm.

**Comment by meerkat-citronella** [comment]
We were able to work with this and implemented it. Thanks for all your help!

**Comment by rsuwa** [comment]
There is a problem with the material-ui style not being applied to [Dialog components](https://material-ui.com/api/dialog/).

What is the solution to this problem?

Here is simple example: https://codesandbox.io/s/recursing-star-gqx6p?file=/src/App.js

**Comment by Josef37** [comment]
> There is a problem with the material-ui style not being applied to [Dialog components](https://material-ui.com/api/dialog/).

You could use the `container` prop on [Modals](https://material-ui.com/api/modal/), which Dialogs inherit. Just provide anything inside the shadow root.
