### ISSUE TITLE
Demo URL is not opening the demo website.

### ISSUE THREAD

**Issue by ashwamegh** [Wildhoney/ReactShadow#85]
<img width="1053" alt="Screenshot 2020-07-23 at 6 02 07 PM" src="https://user-images.githubusercontent.com/7360968/88286610-a3d36d80-cd0e-11ea-981c-173e3a17fdd3.png">

**Comment by Wildhoney** [comment]
Sorry, yeh, my Heroku account ran out of its free dyno hours &mdash; I need to move it to Vercel or somewhere else, or dip my hand in my pocket to pay for a hobby account on Heroku.

It'll be back to normal on the 1st of August, not great I realise!

**Comment by ashwamegh** [comment]
okay 😅 , For the time being if you want, I can host it. 👍

**Comment by Wildhoney** [comment]
Thanks yeh, send me the URL once you've managed to deploy it, and I will update the URL until August. Appreciated @ashwamegh!

**Comment by ashwamegh** [comment]
@Wildhoney Ahh! here it is -> https://react-shadow-2.herokuapp.com/

**Comment by Wildhoney** [comment]
Thanks! Updated 🥳

**Comment by ashwamegh** [comment]
@Wildhoney Is your site up, I will remove this Heroku app then?

**Comment by Wildhoney** [comment]
Thanks! Yep it is working for the moment. I've updated it again.

See you at the end of August! :)

**Comment by Wildhoney** [comment]
I've added yours as the *alternative* link in README: https://github.com/Wildhoney/ReactShadow/blob/master/README.md

**Comment by ashwamegh** [comment]
Okay, see you at the end of August 😅
